// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://upfutrvassvhfjoafpoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwZnV0cnZhc3N2aGZqb2FmcG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4OTgzMzUsImV4cCI6MjA0OTQ3NDMzNX0.ttZt_DQ64ev5q6KqpCFhiSSQocoRySdA1JorvAaKwEU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);